server:
  port: 9999
  servlet:    context-path: /blue
spring:  datasource:    url: jdbc:mysql://localhost:3306/gg?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver  jpa:    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect 
    show-sql: true
    hibernate:      ddl-auto: updatecbs:
   imagesPath: file:D:\desk\freework\X-admin-v2.2\houtai\bluewhale\image\
mybatis:  type-aliases-package: com.yy.spring.entity
  mapper-locations:  - classpath:mapper/*.xml
logging:  level:    com.yy.spring.dao: debug